// ── Types ────────────────────────────────────────────────────────────────────

export interface MetaDeck {
  id: string;
  champion: string;
  fullName: string;
  domain: string;
  secondDomain: string;
  archetype: 'Midrange' | 'Miracle' | 'Aggro' | 'Control' | 'Combo' | 'Tempo';
  tier: 'S' | 'A' | 'B' | 'C';
  description: string;
  playstyle: string;
  difficulty: 'Débutant' | 'Intermédiaire' | 'Expert';
  conversionRate: number;   // Day 2 conversion %
  metaShare: number;        // % représentation
  tournament: string;
  placement: string;        // ex: "🥇 Vainqueur", "Top 4", "Top 8"
  keyCards: string[];
  strengths: string[];
  weaknesses: string[];
  // Résultats par tournoi
  results: {
    event: string;
    date: string;
    players: number;
    placement: string;
    notes: string;
  }[];
}

// ── Données méta post-Vegas (mars 2026) ──────────────────────────────────────

type RawMetaDeck = MetaDeck & { winRate?: number };

export const RAW_META_DECKS: RawMetaDeck[] = [
  {
    id: 'draven-midrange',
    champion: 'Draven',
    fullName: 'Draven Glorious Executioner — Midrange',
    domain: 'Fury',
    secondDomain: 'Chaos',
    archetype: 'Midrange',
    tier: 'S',
    description: 'Le deck le plus dominant de Spiritforged. Combine des unités Fury efficaces avec la synergie Darius/Kai\'Sa et Spinning Axes pour une pression constante. Gagne les showdowns et contrôle le battlefield.',
    playstyle: 'Joue des unités midrange solides, utilise Spinning Axe pour recycler et draw, et cherche à contrôler le battlefield tour après tour. Plus linéaire que la version Miracle, plus facile à prendre en main.',
    difficulty: 'Intermédiaire',
    winRate: 62.4,
    conversionRate: 37,
    metaShare: 18,
    tournament: 'RQ Las Vegas — 1er place',
    placement: '🥇 Vainqueur Las Vegas',
    keyCards: ['Spinning Axe', 'Darius Trifarian', 'Kai\'Sa', 'Rebuke', 'Ride the Wind'],
    strengths: ['Meilleur winrate du jeu', 'Très consistant en Swiss', 'Deux archetypes = difficile à counter', 'Forte capacité de draw'],
    weaknesses: ['Métagame construit pour le battre', 'Vulnerable aux decks "miracle" bien joués', 'Les meilleurs joueurs sur d\'autres légendes peuvent l\'overperform'],
    results: [
      { event: 'RQ Las Vegas', date: 'Mars 2026', players: 1670, placement: '🥇 Vainqueur + Top 4 ×4', notes: 'Domine la meta, 5/8 top 8 slots, 4 semi-finalistes sur 4' },
      { event: 'RQ Bologna', date: 'Fév. 2026', players: 1719, placement: 'Top 8 ×3', notes: 'Top conversion rate mais éliminé en QF par les control decks' },
      { event: 'RQ Chengdu (Chine)', date: 'Jan. 2026', players: 530, placement: '🥇 Vainqueur', notes: '1er des deux tournois China remportés par Draven Midrange' },
      { event: 'RQ Fuzhou (Chine)', date: 'Jan. 2026', players: 480, placement: '🥇 Vainqueur', notes: 'Domination totale, représentait >50% du Top 64' },
    ],
  },
  {
    id: 'draven-miracle',
    champion: 'Draven',
    fullName: 'Draven Glorious Executioner — Miracle',
    domain: 'Fury',
    secondDomain: 'Chaos',
    archetype: 'Miracle',
    tier: 'S',
    description: 'La version explosive de Draven. Utilise Ezreal Prodigy + Called Shot pour draw massivement, puis pose plusieurs Rhasa the Sunderer et Battering Rams en un seul tour. Impossible à counter en un seul gameplan.',
    playstyle: 'Setup patient jusqu\'au tour "Miracle" : combo Called Shot + Ezreal Prodigy pour vider le deck, puis dump toutes les unités gratuites. Deux builds différents = très difficile à préparer pour l\'adversaire.',
    difficulty: 'Expert',
    winRate: 62.4,
    conversionRate: 37,
    metaShare: 18,
    tournament: 'RQ Las Vegas — 1er place',
    placement: '🥇 Vainqueur Las Vegas',
    keyCards: ['Called Shot', 'Ezreal Prodigy', 'Rhasa the Sunderer', 'Battering Ram', 'Hidden cards'],
    strengths: ['Tours explosifs impossibles à répondre', 'Meilleure version en métagame control', 'Partage les stats de Draven Midrange'],
    weaknesses: ['Plus difficile à jouer', 'Nécessite connaissance approfondie du deck', 'Vulnerable aux disruptions sur le setup'],
    results: [
      { event: 'RQ Las Vegas', date: 'Mars 2026', players: 1670, placement: '🥇 Vainqueur + Top 4 ×2', notes: 'Deux Midrange et deux Miracle en semi-finales, perfect balance' },
      { event: 'RQ Bologna', date: 'Fév. 2026', players: 1719, placement: 'Top 8', notes: 'Meilleure version de Draven à Bologna, surpasse le Midrange' },
    ],
  },
  {
    id: 'irelia-tempo',
    champion: 'Irelia',
    fullName: 'Irelia Blade Dancer — Tempo',
    domain: 'Calm',
    secondDomain: 'Chaos',
    archetype: 'Tempo',
    tier: 'S',
    description: 'La légende la plus constante de Spiritforged après Draven. Présente dans chaque Top 8 en China et en Occident. Son ability "Ready a unit" combinée avec Stellacorn Herder génère une card advantage massive.',
    playstyle: 'Développe le board avec des unités mobiles, utilise Ride the Wind et Charm pour repositionner et draw. Stellacorn Herder = draw 2-3 cartes par tour si bien protégée. Timing critique sur l\'ability.',
    difficulty: 'Expert',
    winRate: 50.0,
    conversionRate: 22,
    metaShare: 14,
    tournament: 'RQ Las Vegas — Top 8',
    placement: 'Top 8 chaque Regional',
    keyCards: ['Stellacorn Herder', 'Ride the Wind', 'Charm', 'The Syren', 'En Garde', 'Discipline'],
    strengths: ['Top 8 dans chaque Regional Spiritforged', 'Card draw exceptionnel', 'Forte protection contre les removal', 'Angles d\'attaque uniques'],
    weaknesses: ['0 finale en 6 tournois majeurs', 'Matchup difficile vs Ezreal', 'Mauvais draws peuvent bloquer complètement'],
    results: [
      { event: 'RQ Las Vegas', date: 'Mars 2026', players: 1670, placement: 'Top 8', notes: 'Présente mais éliminée par Draven en QF' },
      { event: 'RQ Bologna', date: 'Fév. 2026', players: 1719, placement: 'Top 4', notes: 'Meilleur résultat occidental, perd en semi vs Ezreal' },
      { event: 'RQ Dalian (Chine)', date: 'Jan. 2026', players: 420, placement: 'Top 8', notes: 'Meilleur conversion rate du tournoi, dépasse Draven' },
      { event: 'RQ Nanjing (Chine)', date: 'Fév. 2026', players: 390, placement: 'Top 8', notes: '2ème conversion rate derrière Annie' },
    ],
  },
  {
    id: 'ezreal-control',
    champion: 'Ezreal',
    fullName: 'Ezreal Prodigal Explorer — Control',
    domain: 'Cunning',
    secondDomain: 'Chaos',
    archetype: 'Control',
    tier: 'S',
    description: 'Vainqueur de Bologna (AlanZQ). Deck control par excellence : control le board, draw énormément, et finit la game avec des units efficaces. Vex est devenu un staple après la performance de Vegas.',
    playstyle: 'Joue lentement, répond à chaque menace, puis prend le board dans les tours tardifs. Stacked Deck + Called Shot + Ezreal Prodigy = main permanente. Vex rend le combat cauchemardesque pour l\'adversaire.',
    difficulty: 'Expert',
    conversionRate: 18,
    metaShare: 8,
    tournament: 'RQ Bologna — 🥇 Vainqueur',
    placement: '🥇 Vainqueur Bologna',
    keyCards: ['Stacked Deck', 'Called Shot', 'Ezreal Prodigy', 'Vex', 'Tideturner', 'Edge of Night'],
    strengths: ['Plafond de skill très élevé', 'Extrêmement flexible', 'Favorisé par les top pilots', 'Bat Draven Miracle dans les mains expertes'],
    weaknesses: ['Courbe d\'apprentissage extrême', 'Un mauvais choix = lose', 'Difficile à adapter rapidement'],
    results: [
      { event: 'RQ Bologna', date: 'Fév. 2026', players: 1719, placement: '🥇 Vainqueur (AlanZQ, undefeated)', notes: 'Undefeated sur 13 rounds de Swiss, performance légendaire' },
      { event: 'RQ Las Vegas', date: 'Mars 2026', players: 1670, placement: 'Top 8', notes: 'Peu représenté, "une semaine n\'est pas assez pour apprendre le deck"' },
    ],
  },
  {
    id: 'kaisa-control',
    champion: "Kai'Sa",
    fullName: "Kai'Sa Daughter of the Void — Control",
    domain: 'Fury',
    secondDomain: 'Mind',
    archetype: 'Control',
    tier: 'S',
    description: 'Meilleure légende control avant l\'émergence des builds Miracle. Son ability donne 1 Power gratuit pour les sorts, rendant Hextech Ray et Falling Star extrêmement efficaces. Vainqueur du Regional Nanjing.',
    playstyle: 'Board control via spells efficients, accumule l\'avantage de cartes avec OGN-114, puis close la game avec ses units. Fury/Mind offre la gamme de spells la plus large du jeu.',
    difficulty: 'Intermédiaire',
    conversionRate: 19,
    metaShare: 11,
    tournament: 'RQ Nanjing (Chine) — 🥇 Vainqueur',
    placement: '🥇 Vainqueur Nanjing',
    keyCards: ['Hextech Ray', 'Falling Star', 'Void Seeker', 'Stupefy', 'Singularity', 'Icathian Rain'],
    strengths: ['Spells très efficaces grâce à l\'ability', 'Card advantage solide', 'Large pool de spells disponibles', 'Bonne flexibilité de build'],
    weaknesses: ['Problème contre les builds Miracle', 'Vulnérable aux tours multi-units', 'Moins dominant depuis Bologna'],
    results: [
      { event: 'RQ Nanjing (Chine)', date: 'Fév. 2026', players: 390, placement: '🥇 Vainqueur', notes: 'Victoire propre dans un méta plus ouvert' },
      { event: 'RQ Dalian (Chine)', date: 'Jan. 2026', players: 420, placement: 'Top 4', notes: 'Finale surprise, joue control vs Ezreal' },
      { event: 'RQ Bologna', date: 'Fév. 2026', players: 1719, placement: 'Top 8', notes: '50.4% WR, solid mais pas dominant' },
      { event: 'RQ Las Vegas', date: 'Mars 2026', players: 1670, placement: 'Top 32', notes: 'Aucun Kai\'Sa en Top 8, deck en difficulté face au Miracle' },
    ],
  },
  {
    id: 'annie-aggro',
    champion: 'Annie',
    fullName: 'Annie Dark Child — Aggro',
    domain: 'Fury',
    secondDomain: 'Chaos',
    archetype: 'Aggro',
    tier: 'A',
    description: 'Meilleure légende aggressive de Spiritforged. Son ability active 2 Runes à la fin de son tour, permettant des réactions en dehors de son propre tour. Vainqueur du Regional Fuzhou (Chine).',
    playstyle: 'Snowball tôt, score des points rapidement avant que l\'adversaire stabilise. Cards low-cost, pression constante. Problème vs les builds Miracle qui peuvent stabiler et contre-attaquer massivement.',
    difficulty: 'Débutant',
    conversionRate: 15,
    metaShare: 4,
    tournament: 'RQ Fuzhou (Chine) — 🥇 Vainqueur',
    placement: '🥇 Vainqueur Fuzhou',
    keyCards: ['SFD-025', 'SFD-021', 'OGN-192 (side)', 'Units low-cost Fury/Chaos'],
    strengths: ['Idéale pour débuter', 'Très rapide', 'Bonne réactivité grâce à l\'ability', 'Forte en bo1'],
    weaknesses: ['Mauvais matchup vs Miracle', 'Popularité effondrée à Las Vegas (23ème)', 'Ralentie par les decks control capables de stabiliser'],
    results: [
      { event: 'RQ Fuzhou (Chine)', date: 'Jan. 2026', players: 480, placement: '🥇 Vainqueur', notes: 'Meilleure aggro du méta pre-Bologna' },
      { event: 'RQ Nanjing (Chine)', date: 'Fév. 2026', players: 390, placement: 'Top 4 + Best conversion', notes: 'Meilleur taux de conversion ET vainqueur' },
      { event: 'RQ Bologna', date: 'Fév. 2026', players: 1719, placement: 'Top 32', notes: 'High conversion rate mais aucun Annie en Top 8' },
      { event: 'RQ Las Vegas', date: 'Mars 2026', players: 1670, placement: '23ème popularité', notes: 'Effondrement total en représentation, méta trop Miracle' },
    ],
  },
  {
    id: 'jax-offmeta',
    champion: 'Jax',
    fullName: 'Jax Grandmaster at Arms — Off-Meta',
    domain: 'Order',
    secondDomain: 'Fury',
    archetype: 'Midrange',
    tier: 'B',
    description: 'La grosse surprise de Las Vegas. TheVeryBestGamer a propulsé Jax en Top 8 avec une liste que personne n\'attendait. Toujours un joueur trouvant un moyen de passer dans les tournois majeurs.',
    playstyle: 'Unités Order/Fury solides, quelques tools de board control. Pas de consensus sur la meilleure liste, ce qui le rend imprévisible. Jax fait régulièrement des Top 8 surprise dans les grands events.',
    difficulty: 'Intermédiaire',
    conversionRate: 12,
    metaShare: 3,
    tournament: 'RQ Las Vegas — Top 8',
    placement: 'Top 8 Las Vegas',
    keyCards: ['Order/Fury units', 'Board control tools'],
    strengths: ['Imprévisible, peu de counter-play préparé', 'Régulièrement présent en Top 8 surprise', 'Adapté par des joueurs créatifs'],
    weaknesses: ['Pas de consensus sur la liste', 'Stats faibles globalement', 'Conversion rate basse hors top players'],
    results: [
      { event: 'RQ Las Vegas', date: 'Mars 2026', players: 1670, placement: 'Top 8 (TheVeryBestGamer)', notes: 'Grosse surprise, seul non-Draven en Top 4 à avoir tenu autant' },
      { event: 'RQ Bologna', date: 'Fév. 2026', players: 1719, placement: 'Top 64', notes: '2ème Top 8 en 6 tournois Spiritforged' },
    ],
  },
  {
    id: 'sett-control',
    champion: 'Sett',
    fullName: 'Sett The Boss — Control',
    domain: 'Fury',
    secondDomain: 'Body',
    archetype: 'Control',
    tier: 'A',
    description: '2ème meilleur winrate à Las Vegas (55.3%). Body legends avec SFD-097 garantissent presque une victoire en showdown. Sett est l\'option control la plus sous-estimée du méta actuel.',
    playstyle: 'Entre en showdown avec SFD-097 et les prend quasi-toujours. Grind value, control le board, et ferme la game avec des units Body solides. Moins explosif que les autres top decks mais très consistant.',
    difficulty: 'Intermédiaire',
    winRate: 55.3,
    conversionRate: 14,
    metaShare: 5,
    tournament: 'RQ Nanjing — Top 16',
    placement: 'Top 16 Nanjing',
    keyCards: ['SFD-097', 'Body units', 'Fury spells'],
    strengths: ['2ème meilleur WR à Vegas', 'Showdowns quasi-garantis', 'Très peu ciblé par le méta'],
    weaknesses: ['Metagame pas préparé pour lui mais le sera', 'Moins de représentation = moins de data', 'Conversion rate modeste'],
    results: [
      { event: 'RQ Las Vegas', date: 'Mars 2026', players: 1670, placement: 'Top 32', notes: '55.3% WR, 2ème du tournoi, sous-représenté' },
      { event: 'RQ Nanjing (Chine)', date: 'Fév. 2026', players: 390, placement: 'Top 16', notes: '37.5% conversion rate, proche du podium' },
    ],
  },
  {
    id: 'viktor-combo',
    champion: 'Viktor',
    fullName: 'Viktor The Machine Herald — Combo',
    domain: 'Knowledge',
    secondDomain: 'Chaos',
    archetype: 'Combo',
    tier: 'A',
    description: 'Seule légende hors Chaos à atteindre le Top 8 à Bologna. Knowledge/Chaos offre une combinaison unique de combo et control. Régulièrement présent en Top 64 dans tous les tournois majeurs.',
    playstyle: 'Build autour de OGN-160 (Miracle shell) ou d\'une stratégie combo Knowledge. Setup des synergies au fil des tours, puis éclate avec un tour décisif. Nécessite de la patience et une bonne lecture du board.',
    difficulty: 'Expert',
    winRate: 49,
    conversionRate: 15,
    metaShare: 6,
    tournament: 'RQ Bologna — Top 8',
    placement: 'Top 8 Bologna',
    keyCards: ['OGN-160', 'Knowledge spells', 'Chaos units'],
    strengths: ['Seule non-Chaos en Top 8 Bologna', 'Combo très puissant si setup', 'Peu anticipé par le méta'],
    weaknesses: ['Setup peut être disrupté', 'WR moyen globalement', 'Matchup difficile vs les decks agressifs'],
    results: [
      { event: 'RQ Bologna', date: 'Fév. 2026', players: 1719, placement: 'Top 8', notes: 'Seule légende sans Chaos en Top 8' },
      { event: 'RQ Chengdu (Chine)', date: 'Jan. 2026', players: 530, placement: 'Top 32', notes: '2 joueurs en Top 64' },
    ],
  },
  {
    id: 'fiora-combo',
    champion: 'Fiora',
    fullName: 'Fiora Grand Duelist — Combo',
    domain: 'Body',
    secondDomain: 'Order',
    archetype: 'Combo',
    tier: 'A',
    description: 'La légende combo basée sur OGN-242. Constamment présente en Top 8 en China (QF dans chaque tournoi). Moins performante en Occident mais reste un tier A solide dans les bonnes mains.',
    playstyle: 'Setup OGN-242 (gear combo) et ferme la game avec un équipement impossible à répondre. Les meilleurs résultats viennent des builds OGN-242, pas du Midrange initial.',
    difficulty: 'Expert',
    winRate: 47,
    conversionRate: 9,
    metaShare: 4,
    tournament: 'RQ Fuzhou — Top 4',
    placement: 'Top 4 Fuzhou',
    keyCards: ['OGN-242', 'Body units', 'Order gear'],
    strengths: ['QF dans chaque tournoi China', 'Combo parfois impossible à stopper', 'Imprévisible'],
    weaknesses: ['Vulnerable au gear removal', 'Conversion rate la plus basse du Tier 1', 'Moins performante en Occident'],
    results: [
      { event: 'RQ Fuzhou (Chine)', date: 'Jan. 2026', players: 480, placement: 'Top 4', notes: 'Finales via le build midrange' },
      { event: 'RQ Dalian (Chine)', date: 'Jan. 2026', players: 420, placement: 'Top 8', notes: 'Build OGN-242 dominant' },
      { event: 'RQ Nanjing (Chine)', date: 'Fév. 2026', players: 390, placement: 'Top 8', notes: 'Confirme sa régularité chinoise' },
      { event: 'RQ Bologna', date: 'Fév. 2026', players: 1719, placement: 'Top 64', notes: 'Moins impactante en Occident' },
    ],
  },
  {
    id: 'miss-fortune-aggro',
    champion: 'Miss Fortune',
    fullName: 'Miss Fortune Bounty Hunter — Aggro',
    domain: 'Body',
    secondDomain: 'Chaos',
    archetype: 'Aggro',
    tier: 'A',
    description: "Finaliste de Bologna (2ème place). Miss Fortune exploite OGN-160 pour des tours explosifs combinés à des unités Body agressives. Sa capacité Double Up permet de frapper plusieurs Battlefields en un tour.",
    playstyle: "Développez des unités Body low-cost tôt. Activez la légende pour frapper deux fois et scorer. OGN-160 permet des combos dévastateurs en milieu de partie.",
    difficulty: 'Intermédiaire',
    winRate: 52,
    conversionRate: 16,
    metaShare: 5,
    tournament: 'RQ Bologna — 🥈 Finaliste',
    placement: '🥈 Finaliste Bologna',
    keyCards: ['OGN-160', 'Miss Fortune Captain', 'Double Up', 'Make it Rain', 'Gangplank'],
    strengths: ["Finaliste Bologna, résultats prouvés", "Double Up = pression sur 2 battlefields", "Bonne synergie Body/Chaos"],
    weaknesses: ["Deuxième meilleur résultat mais pas gagnante", "Dépendante de OGN-160", "Moins dominante à Las Vegas"],
    results: [
      { event: 'RQ Bologna', date: 'Fév. 2026', players: 1719, placement: '🥈 Finaliste', notes: 'Meilleure performance hors Draven/Ezreal' },
      { event: 'RQ Las Vegas', date: 'Mars 2026', players: 1670, placement: 'Top 8', notes: 'Présente mais éliminée en QF' },
    ],
  },
  {
    id: 'sivir-miracle',
    champion: 'Sivir',
    fullName: 'Sivir Battle Mistress — Miracle',
    domain: 'Body',
    secondDomain: 'Chaos',
    archetype: 'Miracle',
    tier: 'A',
    description: "Vainqueur du Regional Dalian. Sivir Miracle utilise la même shell Miracle que Draven mais avec une Légende plus défensive. La Battle Mistress donne une réaction gratuite, rendant les Showdowns très favorables.",
    playstyle: "Gérez le board défensivement grâce à l'ability de Sivir. Setup le combo Miracle pour un tour décisif. Plus durable que Draven Miracle en raison des outils de défense.",
    difficulty: 'Expert',
    winRate: 48,
    conversionRate: 14,
    metaShare: 4,
    tournament: 'RQ Dalian — Top 4',
    placement: 'Top 4 Dalian',
    keyCards: ['Sivir Mercenary', 'Called Shot', 'Body units', 'Ricochet', 'Blade Whirl'],
    strengths: ["Vainqueur Dalian (Chine)", "Réaction gratuite = avantage en showdown", "Shell Miracle efficace"],
    weaknesses: ["Moins dominant que Draven Miracle globalement", "Expert level uniquement", "Peu jouée en Occident"],
    results: [
      { event: 'RQ Dalian (Chine)', date: 'Jan. 2026', players: 420, placement: 'Top 4', notes: 'Finale Kai\'Sa vs Sivir Miracle' },
      { event: 'RQ Las Vegas', date: 'Mars 2026', players: 1670, placement: 'Top 32', notes: 'Représentation limitée mais résultats corrects' },
    ],
  },
  {
    id: 'leona-control',
    champion: 'Leona',
    fullName: 'Leona Radiant Dawn — Control',
    domain: 'Calm',
    secondDomain: 'Order',
    archetype: 'Control',
    tier: 'B',
    description: "Deck control basé sur la Sunlight mechanic de Leona. Accumule des Daybreak effects pour contrôler le board et fermer la partie avec des unités Order/Calm impressionnantes.",
    playstyle: "Déclenchez les effets Daybreak chaque tour pour maintenir la pression. Leona protège ses unités et peut stun les ennemis. Late game très solide grâce aux effets Nightfall.",
    difficulty: 'Intermédiaire',
    winRate: 44,
    conversionRate: 10,
    metaShare: 2,
    tournament: 'Regional China — Top 16',
    placement: 'Top 16 China Opens',
    keyCards: ['Leona Zealot', 'Daybreak cards', 'Nightfall', 'Eclipse Dragon', 'Solari'],
    strengths: ["Très bon contre les decks aggro", "Daybreak/Nightfall offre de la consistance", "Légende solide en midrange"],
    weaknesses: ["Lente contre les decks Miracle", "Card draw limité", "Peu représentée en Occident"],
    results: [
      { event: 'China Opens', date: 'Jan. 2026', players: 390, placement: 'Top 16', notes: 'Régulièrement présente en China Opens' },
    ],
  },
  {
    id: 'ornn-forge',
    champion: 'Ornn',
    fullName: 'Ornn Fire Below the Mountain — Forge',
    domain: 'Calm',
    secondDomain: 'Mind',
    archetype: 'Control',
    tier: 'B',
    description: "Deck Forge avec Ornn. Fabrique des artefacts puissants avec l'ability d'Ornn pour équiper vos unités. Combiné avec des sorts Knowledge pour un contrôle total du board.",
    playstyle: "Jouez lentement et fabriquez des Forgefire articles chaque tour. Ornn réduit le coût de vos équipements, permettant de gear plusieurs unités rapidement. Late game imbattable.",
    difficulty: 'Expert',
    winRate: 43,
    conversionRate: 9,
    metaShare: 1.5,
    tournament: 'Regional China — Top 32',
    placement: 'Top 32 multiple',
    keyCards: ['Ornn Forge God', 'Forgefire', 'Demacian artifacts', 'Heartsteel', 'Vault Breaker'],
    strengths: ["Gear advantage unique", "Late game quasi-imbattable si non rushé", "Scaling exceptionnel"],
    weaknesses: ["Trop lent en early game", "Vulnerable aux aggro", "Complexe à masteriser"],
    results: [
      { event: 'China Opens', date: 'Jan. 2026', players: 420, placement: 'Top 32', notes: 'Présent mais éliminé avant le cut' },
    ],
  },
  {
    id: 'azir-control',
    champion: 'Azir',
    fullName: 'Azir Emperor of the Sands — Control',
    domain: 'Calm',
    secondDomain: 'Order',
    archetype: 'Control',
    tier: 'B',
    description: "Présent dans plusieurs Top 8 China. Azir invoque des soldats de sable pour contrôler le board et marquer des points via le contrôle des Battlefields. Mécanique unique qui confuse l'adversaire.",
    playstyle: "Invocez des Soldats de Sable pour gagner en board presence sans dépenser vos runes. Azir permet d'attaquer et de défendre simultanément grâce à ses soldats. Scoring continu via Hold.",
    difficulty: 'Expert',
    winRate: 46,
    conversionRate: 11,
    metaShare: 3,
    tournament: 'RQ Fuzhou — Top 8',
    placement: 'Top 8 Fuzhou',
    keyCards: ['Azir Sovereign', 'Sand Soldier', 'Emperor\'s Divide', 'Rite of Calling', 'Xerxa\'Reth'],
    strengths: ["Board presence permanente via soldats", "Azir présent à Fuzhou Top 8", "Unique gameplan difficile à counter"],
    weaknesses: ["Curve lente vs aggro", "Soldats faibles vs removal de masse", "Exigeant en skill"],
    results: [
      { event: 'RQ Fuzhou (Chine)', date: 'Jan. 2026', players: 480, placement: 'Top 8', notes: 'Surprise du tournoi chinois' },
    ],
  },
];

// Export public sans les winrates
export const META_DECKS: MetaDeck[] = RAW_META_DECKS.map(({ winRate, ...rest }) => rest);

// ── Données legacy (decks sauvegardés sample) ─────────────────────────────────

export interface Deck {
  id: string;
  name: string;
  author: string;
  domain: string;
  description: string;
  cards: { id: string; name: string; count: number }[];
  wins: number;
  losses: number;
  views: number;
  createdAt: string;
  tags: string[];
}

export const SAMPLE_DECKS: Deck[] = [];

// ── Tournois majeurs ──────────────────────────────────────────────────────────

export interface Tournament {
  id: string;
  name: string;
  date: string;
  location: string;
  players: number;
  prizePool?: string;
  winner: string;
  winnerDomain: string;
  top8: { legend: string; player?: string; placement: string }[];
}

export const MAJOR_TOURNAMENTS: Tournament[] = [
  {
    id: 'vegas-2026',
    name: 'Regional Qualifier Las Vegas',
    date: '28 Fév – 1 Mars 2026',
    location: '🇺🇸 Las Vegas, USA',
    players: 1670,
    prizePool: '$25 000',
    winner: 'Draven Midrange',
    winnerDomain: 'Fury',
    top8: [
      { legend: 'Draven Midrange', player: 'Samdsherman', placement: '🥇 1er' },
      { legend: 'Draven Miracle', placement: '🥈 2ème' },
      { legend: 'Draven Midrange', placement: '🥉 3ème' },
      { legend: 'Draven Miracle', placement: '4ème' },
      { legend: 'Ezreal', player: 'Alanzq', placement: 'Top 8' },
      { legend: 'Jax', player: 'TheVeryBestGamer', placement: 'Top 8' },
      { legend: 'Irelia', placement: 'Top 8' },
      { legend: 'Miss Fortune', placement: 'Top 8' },
    ],
  },
  {
    id: 'bologna-2026',
    name: 'Regional Qualifier Bologna',
    date: 'Fév. 2026',
    location: '🇮🇹 Bologna, Italie',
    players: 1719,
    winner: 'Ezreal',
    winnerDomain: 'Cunning',
    top8: [
      { legend: 'Ezreal', player: 'AlanZQ (undefeated)', placement: '🥇 1er' },
      { legend: 'Miss Fortune', placement: '🥈 2ème' },
      { legend: 'Irelia', placement: 'Top 4' },
      { legend: 'Draven', placement: 'Top 8 ×3' },
      { legend: 'Viktor', placement: 'Top 8' },
    ],
  },
  {
    id: 'nanjing-2026',
    name: 'Regional Open Nanjing',
    date: 'Fév. 2026',
    location: '🇨🇳 Nanjing, Chine',
    players: 390,
    winner: "Kai'Sa / Annie",
    winnerDomain: 'Fury',
    top8: [
      { legend: 'Annie', placement: '🥇 Vainqueur (meilleure conversion)' },
      { legend: "Kai'Sa", placement: 'Top 4' },
      { legend: 'Irelia', placement: 'Top 8' },
      { legend: 'Draven', placement: 'Top 8' },
      { legend: 'Sett', placement: 'Top 8 (37.5% conversion)' },
    ],
  },
  {
    id: 'dalian-2026',
    name: 'Regional Open Dalian',
    date: 'Jan. 2026',
    location: '🇨🇳 Dalian, Chine',
    players: 420,
    winner: "Kai'Sa",
    winnerDomain: 'Fury',
    top8: [
      { legend: "Kai'Sa", placement: '🥇 Vainqueur (Finale Kai\'Sa vs Ezreal)' },
      { legend: 'Ezreal', placement: '🥈 Finaliste' },
      { legend: 'Irelia', placement: 'Top 8 (meilleure conversion)' },
      { legend: 'Sivir Miracle', placement: 'Top 4' },
      { legend: 'Draven', placement: 'Top 8' },
      { legend: 'Fiora', placement: 'Top 8' },
    ],
  },
  {
    id: 'chengdu-2026',
    name: 'Regional Open Chengdu',
    date: 'Jan. 2026',
    location: '🇨🇳 Chengdu, Chine',
    players: 530,
    winner: 'Draven',
    winnerDomain: 'Fury',
    top8: [
      { legend: 'Draven', placement: '🥇 Vainqueur (Spinning Axe build)' },
      { legend: 'Irelia', placement: 'Top 8' },
      { legend: 'Fiora', placement: 'Top 8' },
      { legend: 'Annie', placement: 'Top 32' },
    ],
  },
  {
    id: 'fuzhou-2026',
    name: 'Regional Open Fuzhou',
    date: 'Jan. 2026',
    location: '🇨🇳 Fuzhou, Chine',
    players: 480,
    winner: 'Annie',
    winnerDomain: 'Fury',
    top8: [
      { legend: 'Annie', placement: '🥇 Vainqueur' },
      { legend: 'Fiora', placement: 'Top 4' },
      { legend: 'Draven', placement: 'Top 8 (>50% du Top 64)' },
      { legend: 'Irelia', placement: 'Top 8' },
      { legend: 'Azir', placement: 'Top 8' },
    ],
  },
];

// ── Decks Hors-Méta ─────────────────────────────────────────────────────────

export const OFFMETA_DECKS: RawMetaDeck[] = [
  {
    id: 'teemo-mushroom',
    champion: 'Teemo',
    fullName: 'Teemo Swift Scout — Mushroom',
    domain: 'Cunning',
    secondDomain: 'Chaos',
    archetype: 'Control',
    tier: 'C',
    description: 'Deck fun basé sur les champignons et la mécaniques Hidden. Contrôle le board avec des pièges et utilise Teemo pour scouter.',
    playstyle: 'Placez des mushrooms sur le board pour contrôler les mouvements adverses. Teemo permet de révéler les cartes cachées et de récuperer vos units.',
    difficulty: 'Intermédiaire',
    winRate: 38,
    conversionRate: 5,
    metaShare: 1,
    tournament: 'Fun Deck',
    placement: 'Non compétitif',
    keyCards: ['Teemo', 'Mushroom', 'Guerrilla', 'Camouflage'],
    strengths: ['Fun à jouer', 'Surprise l\'adversaire', 'Contrôle de zone'],
    weaknesses: ['Trop slow', 'Pas assez de support', 'Weak aux aggro'],
    results: [],
  },
  {
    id: 'heimer-turret',
    champion: 'Heimerdinger',
    fullName: 'Heimerdinger Inventor — Turret',
    domain: 'Knowledge',
    secondDomain: 'Chaos',
    archetype: 'Control',
    tier: 'C',
    description: 'Deck basé sur les tourelles d\'Heimerdinger. Accumulez des tourelles pour contrôler le board et finish avec des gros spells.',
    playstyle: 'Build des tourelles early pour contrôler le board. Utilisez les upgrades pour rendre vos tourelles plus puissantes.',
    difficulty: 'Expert',
    winRate: 36,
    conversionRate: 3,
    metaShare: 0.5,
    tournament: 'Fun Deck',
    placement: 'Non compétitif',
    keyCards: ['Heimerdinger', 'Turret', 'UPGRADE', 'Flash of Insight'],
    strengths: ['Value enorme', 'Board resistant', 'Late game fort'],
    weaknesses: ['Trop lent', 'Vulnerable aux removal', 'Difficile à masteriser'],
    results: [],
  },
  {
    id: 'volibear-frost',
    champion: 'Volibear',
    fullName: 'Volibear Thunder Lord — Frost',
    domain: 'Order',
    secondDomain: 'Knowledge',
    archetype: 'Control',
    tier: 'C',
    description: 'Deck Frostbite avec Volibear. Contrôlez le board avec des effets de freezing et finish avec des grosses unités.',
    playstyle: 'Utilisez des spells de Frostbite pour contrôler les unités adverses. Volibear buff vos attaques et peut finish la partie.',
    difficulty: 'Intermédiaire',
    winRate: 40,
    conversionRate: 4,
    metaShare: 0.8,
    tournament: 'Fun Deck',
    placement: 'Non compétitif',
    keyCards: ['Volibear', 'Frostbite', 'Stormbringer', 'Glacial Wall'],
    strengths: ['Contrôle total', 'Fun mechanics', 'Bon vs control'],
    weaknesses: ['Slow vs aggro', 'Pas assez de draw', 'Mauvais matchups'],
    results: [],
  },
  {
    id: 'jinx-megavolley',
    champion: 'Jinx',
    fullName: 'Jinx Loose Cannon — Megavolley',
    domain: 'Cunning',
    secondDomain: 'Chaos',
    archetype: 'Aggro',
    tier: 'C',
    description: 'Deck aggro avec Jinx et Super Megavolley. Cartes low-cost avec beaucoup de card draw pour garder la pression.',
    playstyle: 'Jouez des unités aggressive early. Utilisez Jinx pour draw et Super Megavolley pour finish.',
    difficulty: 'Débutant',
    winRate: 42,
    conversionRate: 6,
    metaShare: 1.2,
    tournament: 'Fun Deck',
    placement: 'Non compétitif',
    keyCards: ['Jinx', 'Get Excited', 'Super Megavolley', 'Flame Chompers'],
    strengths: ['Fun à jouer', 'Easy to learn', 'Aggro vs control'],
    weaknesses: ['Pas assez consistent', 'Weak vs removal', 'Mauvais vs board control'],
    results: [],
  },
  {
    id: 'sett-boss',
    champion: 'Sett',
    fullName: 'Sett The Boss — Eyeball',
    domain: 'Chaos',
    secondDomain: 'Body',
    archetype: 'Midrange',
    tier: 'C',
    description: 'Deck basé sur la mécanique The Boss de Sett. Accumulez des yeux pour unlock des effets puissants.',
    playstyle: 'Build des yeux avec vos unités et sorts. Sett devient de plus en plus fort avec chaque œil collecté.',
    difficulty: 'Intermédiaire',
    winRate: 39,
    conversionRate: 4,
    metaShare: 0.7,
    tournament: 'Fun Deck',
    placement: 'Non compétitif',
    keyCards: ['Sett', 'Take the Lead', 'Facelift', 'Headliner'],
    strengths: ['Unique mechanic', 'Scaling bien', 'Fun deck'],
    weaknesses: ['Inconsistent', 'Trop de setup', 'Weak en meta'],
    results: [],
  },
  {
    id: 'fiora-duelist',
    champion: 'Fiora',
    fullName: 'Fiora Grand Duelist — Duel',
    domain: 'Glory',
    secondDomain: 'Order',
    archetype: 'Combo',
    tier: 'C',
    description: 'Deck combo basé sur les duels de Fiora. Gagnez des buffs en tuant des unités adverses lors de duels.',
    playstyle: 'Build Fiora avec des buffs et partez en duel. Chaque kill vous rend plus fort.',
    difficulty: 'Expert',
    winRate: 37,
    conversionRate: 3,
    metaShare: 0.6,
    tournament: 'Fun Deck',
    placement: 'Non compétitif',
    keyCards: ['Fiora', 'Riposte', 'Parry', 'Duel'],
    strengths: ['Combo satisfaisant', 'High skill ceiling', 'Unique playstyle'],
    weaknesses: ['Trop fragile', 'Setup long', 'Vulnerable aux counters'],
    results: [],
  },
  {
    id: 'reksai-tunnel',
    champion: 'Rek\'Sai',
    fullName: 'Rek\'Sai Terror of the Sands — Tunnel',
    domain: 'Void',
    secondDomain: 'Chaos',
    archetype: 'Tempo',
    tier: 'C',
    description: 'Deck basé sur la mécanique Burrow/Unburrow. Cachez vos unités sous terre et ressortir pour des attaques surprise.',
    playstyle: 'Burrow vos unités pour les protéger des attacks. Unburrow pour des attaques surprise et du damage.',
    difficulty: 'Intermédiaire',
    winRate: 38,
    conversionRate: 4,
    metaShare: 0.8,
    tournament: 'Fun Deck',
    placement: 'Non compétitif',
    keyCards: ['Rek\'Sai', 'Burrow', 'Unburrow', 'Tunnel'],
    strengths: ['Fun mechanic', 'Surprise factor', 'Unique gameplay'],
    weaknesses: ['Trop complexe', 'Inconsistent', 'Pas assez de support'],
    results: [],
  },
  {
    id: 'ezreal-poke',
    champion: 'Ezreal',
    fullName: 'Ezreal Prodigal Explorer — Poke',
    domain: 'Cunning',
    secondDomain: 'Knowledge',
    archetype: 'Control',
    tier: 'B',
    description: 'Version alternative d\'Ezreal focusing sur le poke et les sorts. Utilize Ezreal pour poke et control.',
    playstyle: 'Poke l\'adversaire avec Ezreal et spells. Accumulez des Mana Bolts pour finish.',
    difficulty: 'Intermédiaire',
    winRate: 45,
    conversionRate: 8,
    metaShare: 2,
    tournament: 'Off-meta viable',
    placement: 'Top 32',
    keyCards: ['Ezreal', 'Mystic Shot', 'Arcane Shift', 'Mana Bolt'],
    strengths: ['Fun control', 'Good poke', 'Versatile'],
    weaknesses: ['Moins fort que meta', 'Slow start', 'Require skill'],
    results: [],
  },
  {
    id: 'lee-sin-tempo',
    champion: 'Lee Sin',
    fullName: 'Lee Sin Blind Monk — Tempo',
    domain: 'Calm',
    secondDomain: 'Body',
    archetype: 'Tempo',
    tier: 'C',
    description: "Deck basé sur le style de Lee Sin : éjectez les unités adverses pour scorer via des Battlefields vides. Tempo agressif centré sur les mouvements d'unités et le repositionnement.",
    playstyle: "Utilisez Resonating Strike et Dragon's Rage pour éjecter les unités adverses. Lee Sin Centered permet de marquer des points inattendus en repositionnant le board adverse.",
    difficulty: 'Expert',
    winRate: 39,
    conversionRate: 4,
    metaShare: 0.5,
    tournament: 'Fun Deck',
    placement: 'Non compétitif',
    keyCards: ["Lee Sin Centered", "Resonating Strike", "Dragon's Rage", 'Pale Cascade', 'Concussive Palm'],
    strengths: ['Gameplay unique et imprévisible', 'Disruption du board adverse', 'Satisfaisant à jouer'],
    weaknesses: ['Très expert-dépendant', 'Inconsistant sans les bonnes cartes', 'Weak aux decks linéaires'],
    results: [],
  },
  {
    id: 'garen-order',
    champion: 'Garen',
    fullName: 'Garen Might of Demacia — Order',
    domain: 'Body',
    secondDomain: 'Order',
    archetype: 'Aggro',
    tier: 'C',
    description: "Deck d'introduction idéal pour les nouveaux joueurs. Garen joue des unités Body/Order solides avec le keyword Tough. Simple mais efficace pour apprendre les mécaniques de base.",
    playstyle: "Jouez des unités Order séquentiellement pour activer Demacia Rising. Garen Commander protège vos unités avec Tough. Approche directe et facile à prendre en main.",
    difficulty: 'Débutant',
    winRate: 41,
    conversionRate: 5,
    metaShare: 1,
    tournament: 'Starter Deck',
    placement: 'Deck de débutant',
    keyCards: ['Garen Commander', 'Jarvan IV', 'Demacian Soldier', 'Cithria of Cloudfield', 'Brightsteel Formation'],
    strengths: ['Parfait pour apprendre', 'Unités solides', 'Mécaniques simples'],
    weaknesses: ['Trop prévisible en méta', 'Pas de surprise factor', 'Outscaled par les decks complexes'],
    results: [],
  },
  {
    id: 'yasuo-wind',
    champion: 'Yasuo',
    fullName: 'Yasuo Unforgiven — Wind',
    domain: 'Calm',
    secondDomain: 'Chaos',
    archetype: 'Combo',
    tier: 'C',
    description: "Deck Recall avec Yasuo. Renvoyez les unités adverses en Base pour scorer via des Battlefields vides. Yasuo Windrider gagne du Might à chaque unité renvoyée.",
    playstyle: "Utilisez des cartes Recall pour renvoyer les unités adverses en Base. Yasuo en profite pour attaquer des Battlefields dégagés. Chaque Recall buff Yasuo Windrider.",
    difficulty: 'Intermédiaire',
    winRate: 40,
    conversionRate: 4,
    metaShare: 0.8,
    tournament: 'Fun Deck',
    placement: 'Non compétitif',
    keyCards: ['Yasuo Windrider', 'Whirling Death', 'Eye of the Dragon', 'Recall spells', 'Elusive units'],
    strengths: ['Snowball puissant si setup', 'Recall crée des fenêtres offensives', 'Fun à jouer'],
    weaknesses: ['Fragile si Yasuo est supprimé', 'Dépendant du Recall', 'Inconsistant en méta'],
    results: [],
  },
  {
    id: 'rumble-tech',
    champion: 'Rumble',
    fullName: 'Rumble Mechanized Menace — Tech',
    domain: 'Fury',
    secondDomain: 'Mind',
    archetype: 'Midrange',
    tier: 'C',
    description: "Deck Flamespitter avec Rumble. Utilisez les sorts multiples de Rumble pour activer Overheating. Chaque sort après le premier deal des dégâts bonus via la mécanique de surchauffe.",
    playstyle: "Jouez des sorts multiples chaque tour pour activer Overheating. Rumble Scrapper inflige des dégâts bonus à chaque sort joué après le premier. Value engine durable.",
    difficulty: 'Intermédiaire',
    winRate: 38,
    conversionRate: 4,
    metaShare: 0.6,
    tournament: 'Fun Deck',
    placement: 'Non compétitif',
    keyCards: ['Rumble Scrapper', 'Flamespitter', 'Overheating', 'Electro Harpoon', 'Tristana'],
    strengths: ['Damage output unique via Overheating', 'Fun mechanic', 'Bonne value par tour'],
    weaknesses: ['Slow démarrage', 'Peu de board presence', 'Weak vs removal ciblé'],
    results: [],
  },
];
